# Generated by Django 5.2.8 on 2026-01-29 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('telepon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='barang/')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.kategori')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiPenjualan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('total_harga', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('nama_pembeli', models.CharField(blank=True, default='Umum', max_length=100)),
                ('sudah_diretur', models.BooleanField(default=False)),
                ('alasan_retur', models.TextField(blank=True, null=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventaris.barang')),
            ],
        ),
    ]
