# Generated by Django 5.2.8 on 2025-11-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_barang', models.CharField(max_length=20, unique=True)),
                ('nama_barang', models.CharField(max_length=100)),
                ('kategori', models.CharField(max_length=50)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jumlah_stok', models.IntegerField()),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
