# Generated by Django 5.2.8 on 2026-01-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('nama_pembeli', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='inventaris.barang')),
            ],
        ),
    ]
